title: <p align="center"> Shashank Dittakavi </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shashank-dittakvi/">LinkedIn</a> |
  <a href="https://github.com/dshashank14">GitHub</a>
 
  <br>  
  I'm working in the FinTech domain. I have around 8 years of experience in building 
  application in the Java ecosystem
  <br>
  </p>



theme: jekyll-theme-minimal
